server:
  port: 8080
spring:
  datasource:
    # Se DATABASE_URL for injetada pelo Docker, o Spring usa. Senão, adota o padrão local 'corridas_dev'
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/corridas_dev}
    username: ${DB_USERNAME:corridasdb}
    password: ${DB_PASSWORD:C@rR!d@db}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

api:
  security:
    token:
      # Permite injetar um secret forte em produção. Se não houver, usa o padrão.
      secret: ${API_SECURITY_TOKEN_SECRET:teste_secret}

ors:
  api-key: ${ORS_API_KEY:""}
  base-url: ${ORS_BASE_URL:https://api.openrouteservice.org}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    # Corrigido de 'mercado' para o pacote real do seu projeto 'corrida'
    br.ufpb.dsc.corrida: DEBUG
    org.springframework.web: DEBUG