-- =============================================================================
-- Migration V13: Criar tabela feature_flags para o mecanismo de Feature Toggle
-- =============================================================================
-- Estratégia de Cache:
--   Os valores desta tabela são cacheados em memória (Caffeine) com TTL configurável
--   via 'feature-toggle.cache-ttl-seconds'. Mudanças no banco só são propagadas após
--   expiração do cache ou chamada explícita de evicção via FeatureToggleService.
-- =============================================================================

CREATE TABLE feature_flags (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_name    VARCHAR(100) NOT NULL,
    enabled     BOOLEAN NOT NULL DEFAULT FALSE,
    description VARCHAR(255),
    updated_at  TIMESTAMP WITH TIME ZONE
);

-- Índice único na coluna key_name para buscas eficientes e garantia de unicidade
CREATE UNIQUE INDEX idx_feature_flags_key_name ON feature_flags(key_name);

-- =============================================================================
-- Seed: Flags de sistema conhecidas
-- Regra de negócio: todas as flags são criadas com enabled = FALSE por padrão.
-- ON CONFLICT garante idempotência em re-execuções acidentais.
-- =============================================================================
INSERT INTO feature_flags (key_name, enabled, description, updated_at)
VALUES
    ('AUDIT_NEW_PIPELINE', false, 'Enables the new asynchronous audit logging pipeline', CURRENT_TIMESTAMP),
    ('PAYMENT_V2',         false, 'Enables integration with the V2 payment gateway',     CURRENT_TIMESTAMP)
ON CONFLICT (key_name) DO NOTHING;
