name: Integração contínua

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Lint e testes
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./projeto-eq07

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: corridas_dev
          POSTGRES_USER: corridasdb
          POSTGRES_PASSWORD: C@rR!d@db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U corridasdb -d corridas_dev"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Configura JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar dependências e rodar testes
        run: ./mvnw dependency:resolve

      - name: Teste de qualidade de código (lint)
        run: ./mvnw pmd:check   

      - name: Rodar testes unitários
        run: ./mvnw test

      - name: Rodar testes de integração
        run: ./mvnw verify 